---
# Конвертация контейнера в шаблон

- name: Convert CT {{ proxmox_hostname }} to template
  delegate_to: "{{ proxmox_node }}"
  block:
  
  - name: Stop LXC
    community.general.proxmox: &proxmox_lxc
      node        : "{{ proxmox_node }}"
      api_host    : "{{ proxmox_api_host }}"
      api_user    : "{{ proxmox_api_user }}"
      api_password: "{{ proxmox_api_pass }}"
      hostname    : "{{ proxmox_hostname }}"
      state       : stopped
    register: lxc_stopped
    failed_when: false        

  - name: Wait for stopped LXC 
    when: lxc_stopped is changed
    ansible.builtin.pause:
      seconds: "{{ proxmox_wait_sec }}"    

  - name: Convert CT to template
    community.general.proxmox:
      <<: *proxmox_lxc
      state: template
