---
# Плейбук который настраивает проброс видеокарты Nvidia внутрь LXC контейнеров Proxmox
# Требует указания {{ target }} - имени контейнера внутрь которого необходимо прокинуть видеокарту
  
- name: Nvidia passthru in LXC # noqa syntax-check[specific]
  hosts: "{{ target }}"

  tasks:

    - name: Настройка параметров LXC контейнера
      delegate_to: "{{ proxmox_node }}"
      block:

        - name: Определяем мажорный номер nvidia0
          ansible.builtin.shell: set -o pipefail && ls -al /dev/nvidia0 | grep -Po '\d+(?=,)'
          args:
            executable: /bin/bash
          register: _maj_nvidia0
          changed_when: false

        - name: Определяем мажорный номер nvidia-uvm
          ansible.builtin.shell: set -o pipefail && ls -al /dev/nvidia-uvm | grep -Po '\d+(?=,)'
          args:
            executable: /bin/bash
          register: _maj_nvidia_uvm
          changed_when: false

        - name: Конфигурирование контейнера
          ansible.builtin.lineinfile:
            path: /etc/pve/lxc/{{ proxmox_vmid }}.conf
            line: "{{ item }}"
            state: present
          loop:
            - "lxc.cgroup2.devices.allow: c {{ _maj_nvidia0.stdout }}:* rwm"
            - "lxc.cgroup2.devices.allow: c {{ _maj_nvidia_uvm.stdout }}:* rwm"
            - "lxc.mount.entry: /dev/nvidia0 dev/nvidia0 none bind,optional,create=file"
            - "lxc.mount.entry: /dev/nvidiactl dev/nvidiactl none bind,optional,create=file"
            - "lxc.mount.entry: /dev/nvidia-uvm dev/nvidia-uvm none bind,optional,create=file"
            - "lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-uvm-tools none bind,optional,create=file"
          notify: Reboot LXC

    - name: Add non-free repo в sources.list
      ansible.builtin.replace:
        path: /etc/apt/sources.list
        regexp: '^(deb .* {{ ansible_distribution_release }} main).*$'
        replace: '\1 contrib non-free non-free-firmware'
      register: _repo_changed

    - name: Update apt cache # noqa no-handler
      when: _repo_changed is changed
      ansible.builtin.apt:
        update_cache: true

    - name: Install Nvidia package
      ansible.builtin.apt:
        name:
          - libnvcuvid1
          - libnvidia-encode1
          - nvidia-smi
          - linux-headers-amd64
          - nvidia-driver-bin
          - nvtop
      notify: Reboot LXC

    - name: Add nouveau to blacklist
      ansible.builtin.copy:
        content: |
          blacklist nouveau
        dest  : /etc/modprobe.d/blacklist-nouveau.conf
        owner : root
        group : root
        mode  : '0644'
      notify: Reboot LXC

    - name: Добавление модулей Nvidia в черный список
      ansible.builtin.copy:
        content: |
          blacklist nvidia
          blacklist nvidia_uvm
          blacklist nvidia_modeset
          blacklist nvidia_drm
        dest  : /etc/modprobe.d/blacklist-nvidia.conf
        owner : root
        group : root
        mode  : '0644'
      notify: Reboot LXC

  handlers:

    - name: Reboot LXC
      ansible.builtin.reboot:
        reboot_timeout: 300    

